From node:14 as builder

ENV PROJECT_ENV production
ENV NODE_ENV production

COPY package*.json /app/

WORKDIR /app

RUN npm install 

COPY . /app

RUN npm run build


FROM nginx

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/build /app/build